
#阿里数据源
type: com.alibaba.druid.pool.DruidDataSource

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: XUQY
    password: 112652
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
devtools:
  restart:
    enabled: true  #设置开启热部署
    additional-paths: src/main/java #重启目录



